# Generated by Django 5.1.1 on 2024-09-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='project',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
